Storage usage:

SELECT TABLE_CATALOG,
       TABLE_SCHEMA,
       TABLE_NAME,
       ACTIVE_BYTES/1024/1024/1024 AS SIZE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
ORDER BY SIZE_GB DESC

Warehouse_credit_consumption:

SELECT WAREHOUSE_NAME,
       SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_DATE)
GROUP BY WAREHOUSE_NAME;

failed_pipe_loads:

SELECT *
      FROM SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
      WHERE ERROR_COUNT > 0
        AND PIPE_RECEIVED_TIME >= DATEADD('hour', -1, CURRENT_TIMESTAMP());

long-running tasks:

SELECT *
      FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
      WHERE EXECUTION_STATUS = 'RUNNING'
        AND START_TIME < DATEADD('hour', -2, CURRENT_TIMESTAMP())

Query performance:

SELECT USER_NAME,
       AVG(TOTAL_ELAPSED_TIME/1000) AS AVG_EXEC_TIME_SEC
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_DATE)
GROUP BY USER_NAME
ORDER BY AVG_EXEC_TIME_SEC DESC;
